close all; clear all; clc;
hf=figure('Position',[1,21,1366,671], ...
'Name','Basic Inequality Quadratic Example');
fs=20; fa=0.5;
fcolor=[0.000 0.741 0.447];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,1)
x = linspace(-10,10,100);
y = x.^2;
hold on;
h2=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','--', ...
'color',[0 0 0])
hold off;
set(h2,'basevalue',100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y>x^2','fontsize',fs, ...
'fontweight','bold')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,2)
x = linspace(-10,10,100);
y = x.^2;
hold on;
h4=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','--', ...
'color',[0 0 0]);
hold off;
set(h4,'basevalue',-100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y<x^2','fontsize',fs, ...
'fontweight','bold')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,3)
x = linspace(-10,10,100);
y = x.^2;
hold on;
h1=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','-', ...
'color',[0 0 0])
hold off;
set(h1,'basevalue',100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y\geqx^2','fontsize',fs, ...
'fontweight','bold','interpreter','tex')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,4)
x = linspace(-10,10,100);
y = x.^2;
hold on;
h3=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','-', ...
'color',[0 0 0])
hold off;
set(h3,'basevalue',-100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.01)
title('y\leqx^2','fontsize',fs,...
'fontweight','bold','interpreter','tex')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,5)
x = linspace(-10,10,100);
y = -x.^2;
hold on;
h2=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','--', ...
'color',[0 0 0])
hold off;
set(h2,'basevalue',100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y>-x^2','fontsize',fs, ...
'fontweight','bold')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,6)
x = linspace(-10,10,100);
y = -x.^2;
hold on;
h4=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','--', ...
'color',[0 0 0]);
hold off;
set(h4,'basevalue',-100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y<-x^2','fontsize',fs, ...
'fontweight','bold')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,7)
x = linspace(-10,10,100);
y = -x.^2;
hold on;
h1=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','-', ...
'color',[0 0 0])
hold off;
set(h1,'basevalue',100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.1)
title('y\geq-x^2','fontsize',fs, ...
'fontweight','bold','interpreter','tex')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(2,4,8)
x = linspace(-10,10,100);
y = -x.^2;
hold on;
h3=area(x, y);
plot(x,y,'linewidth',5.0,'linestyle','-', ...
'color',[0 0 0])
hold off;
set(h3,'basevalue',-100,'edgecolor',[0 0 0], ...
'facecolor',fcolor, 'facealpha',fa, ...
'hittestarea','off','linestyle','-', ...
'linewidth',0.01)
title('y\leq-x^2','fontsize',fs,...
'fontweight','bold','interpreter','tex')
axis([-10 10 -10 10])
set(gca,'xaxislocation','origin',...
'yaxislocation','origin');
box off; grid on;
