clear all; close all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('Composición de Funciones Trigonométricas Inversas', ...
' en Funciones Trigonométricas'));
vc=[0.00000 0.44700 0.74100];
vc=[1 0 0];
ms=1; %ms=12;
lw=0.5; lw=5;
subplot(2,4,1)
h1=ezplot('sin(asec(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,2)
h1=ezplot('cot(asec(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,3)
h1=ezplot('csc(asec(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,4)
h1=ezplot('tan(asec(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,5)
h1=ezplot('cos(acsc(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,6)
h1=ezplot('tan(acsc(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,7)
h1=ezplot('sec(acsc(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)
subplot(2,4,8)
h1=ezplot('cot(acsc(x))',[-6 6]);
set(h1,'linejoin','round','linestyle','-','linewidth',lw, ...
    'marker','none','markeredgecolor','auto','markerfacecolor','none', ...
    'markersize',ms,'color',vc)