clear all; close all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('Annotation Vertical and Horizontal Alignment',...
' Coordinates Examples Fitboxtext OFF'));
fs=24; fs2=22; fs3=18;
tbp=[0 0.002 1 0.998]; %%[x0 y0 width height]
ecv=[0 0 0];
fbt="off";
lw=1;
lsp="--";
%"-","--",":","-.","none"
ha1=annotation ("textbox",tbp, "string", ...
             {'left-top','(x,y)=(0,1)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha2=annotation ("textbox",tbp, "string", ...
             {'center-top','(x,y)=(0.5,1)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha3=annotation ("textbox",tbp, "string", ...
             {'right-top','(x,y)=(1,1)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ha4=annotation ("textbox",tbp, "string", ...
             {'left-middle','(x,y)=(0,0.5)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor",ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha5=annotation ("textbox",tbp, "string", ...
             {'center-middle','(x,y)=(0.5,0.5)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha6=annotation ("textbox",tbp, "string", ...
             {'right-middle','(x,y)=(1,0.5)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ha7=annotation ("textbox",tbp, "string", ...
             {'left-bottom','(x,y)=(0,0)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha8=annotation ("textbox", tbp, "string", ...
             {'center-bottom','(x,y)=(0.5,0)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha9=annotation ("textbox", tbp, "string", ...
             {'right-bottom','(x,y)=(1,0)'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);