clear all; close all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name','Annotation Examples Fitboxtext OFF');
fs=24; fs2=22; fs3=18;
tbp=[0 0.002 1 0.998]; %%[x0 y0 width height]
ecv=[0 0 0];
fbt="off";
lw=1;
lsp="--";
%"-","--",":","-.","none"
ha1=annotation ("textbox",tbp, "string", ...
             {'Annotation 1 top-left'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha2=annotation ("textbox",tbp, "string", ...
             {'Annotation 2 top-center'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha3=annotation ("textbox",tbp, "string", ...
             {'Annotation 3 top-right'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "top", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ha4=annotation ("textbox",tbp, "string", ...
             {'Annotation 4 middle-left'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor",ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha5=annotation ("textbox",tbp, "string", ...
             {'Annotation 5 middle-center'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha6=annotation ("textbox",tbp, "string", ...
             {'Annotation 6 middle-right'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "middle", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ha7=annotation ("textbox",tbp, "string", ...
             {'Annotation 7 bottom-left'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "left",'linestyle',lsp,'linewidth',lw);
ha8=annotation ("textbox", tbp, "string", ...
             {'Annotation 8 bottom-center'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "center",'linestyle',lsp,'linewidth',lw);
ha9=annotation ("textbox", tbp, "string", ...
             {'Annotation 9 bottom-right'}, ...
             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
             "fitboxtotext", fbt, "verticalalignment", "bottom", ...
             "horizontalalignment", "right",'linestyle',lsp,'linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
##ha10=annotation ("textbox",tbp, "string", ...
##             {'Annotation 10 bottom-left'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "baseline", ...
##             "horizontalalignment", "left",'linestyle','none','linewidth',lw);
##ha11=annotation ("textbox", tbp, "string", ...
##             {'Annotation 11 bottom-center'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "baseline", ...
##             "horizontalalignment", "center",'linestyle','none','linewidth',lw);
##ha12=annotation ("textbox", tbp, "string", ...
##             {'Annotation 12 bottom-right'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "baseline", ...
##             "horizontalalignment", "right",'linestyle','none','linewidth',lw);
##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
##ha13=annotation ("textbox",tbp, "string", ...
##             {'Annotation 13 bottom-left'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "crap", ...
##             "horizontalalignment", "left",'linestyle','none','linewidth',lw);
##ha14=annotation ("textbox", tbp, "string", ...
##             {'Annotation 14 bottom-center'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "crap", ...
##             "horizontalalignment", "center",'linestyle','none','linewidth',lw);
##ha15=annotation ("textbox", tbp, "string", ...
##             {'Annotation 15 bottom-right'}, ...
##             "fontsize", fs3, 'fontweight','bold',"edgecolor", ecv, ...
##             "fitboxtotext", fbt, "verticalalignment", "crap", ...
##             "horizontalalignment", "right",'linestyle','none','linewidth',lw);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%