clear all; close all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('Quince Diagramas de Venn', ...
' de Conjuntos'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
lw=3; fs=20; fs2=20; ms=25; vc1=[0 0 1]; vc2=[1 0 0];
fc=[1 1 1]; fa=1; ec=[0 0 0]; ea=1;
t = linspace(0,2*pi,1000);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
subplot(3,5,1)
annotation ("textbox", [0.185 0.96 0 0], "string", ...
             {'A'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])
axis off;          
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%       
subplot(3,5,2)
annotation ("textbox", [0.35 0.96 0 0], "string", ...
             {'B'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])        
axis off;   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
subplot(3,5,3)
annotation ("textbox", [0.515 0.96 0 0], "string", ...
             {'A'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,4)
annotation ("textbox", [0.68 0.96 0 0], "string", ...
             {'B'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,5)
annotation ("textbox", [0.845 0.96 0 0], "string", ...
             {'U'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',[1 0 0],'facealpha',1, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])
axis off;  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,6)
annotation ("textbox", [0.182 0.66 0 0], "string", ...
             {'A\cupB'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,7)
annotation ("textbox", [0.347 0.66 0 0], "string", ...
             {'A\capB'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])        
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,8)
annotation ("textbox", [0.517 0.66 0 0], "string", ...
             {'A-B=B''-A'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])         
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,9)
annotation ("textbox", [0.685 0.66 0 0], "string", ...
             {'B-A=A''-B'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])          
axis off;  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,10)
annotation ("textbox", [0.845 0.66 0 0], "string", ...
             {'A\DeltaB'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])           
axis off;  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
subplot(3,5,11)
annotation ("textbox", [0.187 0.36 0 0], "string", ...
             {'(A\cupB)''=A''\capB'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])            
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,12)
annotation ("textbox", [0.355 0.36 0 0], "string", ...
             {'(A\capB)''=A''\cupB'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])          
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(3,5,13)
annotation("textbox", [0.52 0.36 0 0], "string", ...
             {'(A-B)''=A''\cupB'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])        
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
subplot(3,5,14)
annotation("textbox", [0.685 0.36 0 0], "string", ...
             {'(B-A)''=A\cupB'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])                
axis off;    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
subplot(3,5,15)
annotation ("textbox", [0.845 0.36 0 0], "string", ...
             {'(A\DeltaB)'''}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
px=[-2 1.25 1.25 -2];
py=[-1.2 -1.2 1.2 1.2];
fill(px,py,'r','linewidth',0.5,'linestyle','-',...
        'facecolor',fc,'facealpha',fa, ...
        'edgecolor',ec,'edgealpha',ea)
        t = linspace(0,2*pi,1000);
x = [cos(t) 1];
y = [sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
x = [cos(t)-0.75 0.25];
y = [sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',1,'edgecolor',[0 0 0], ...
        'facealpha',0,'facecolor',[1 1 1], ...
        'linestyle','-','linewidth',0.5)
axis([-2 1.25 -1.8 1.8])        
axis off; 