close all; clear all; clc;
plot3([0 0 0])
xlabel('xlabel','fontname','Times New Roman', ...
'fontweight','bold','fontsize',24)
ylabel('ylabel','fontname','Times New Roman', ...
'fontweight','bold','fontsize',24)
zlabel('zlabel','fontname','Times New Roman', ...
'fontweight','bold','fontsize',24)