clear all; close all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('LaTeX Interpreter',' con Simbolos Griegos'));
subplot(1,2,1)
text(-2,4,'Con Una Comilla \LaTeX')
title(strcat('\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta', ...
'	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi', ...
'\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega'))
xlabel(strcat('\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta', ...
'	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi', ...
'\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega'))
ylabel(strcat('\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta', ...
'	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi', ...
'\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega'))
text(-7,0,strcat('\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta', ...
'	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi', ...
'\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega'))
axis([-11 11 -11 11]); subplot(1,2,2); warning ("off");
title(strcat("\alpha \beta \gamma \delta \epsilon \zeta \eta \theta", ...
"	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi", ...
"\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega"))
xlabel(strcat("\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta", ...
"	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi", ...
"\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega"))
ylabel(strcat("\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta", ...
"	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi", ...
"\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega"))
text(-7,0,strcat("\alpha	\beta	\gamma \delta	\epsilon	\zeta \eta	\theta", ...
"	\vartheta \iota	\kappa	\lambda \mu	\nu	\xi \o	\pi	\varpi", ...
"\rho	\sigma	\varsigma \tau	\upsilon	\phi \chi	\psi	\omega"))
text(-2,4,"Con Dos Comillas \LaTeX")
axis([-11 11 -11 11])