close all; clear all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('Rosa de Viento',...
' - Wind Rose'));
lw=5; fs=20;
%%%%%%%%%%%%%%
subplot(1,2,1)
h1=rose(2*randn (1e5, 1), 8);
title("rose() angular histogram plot with 8 bins",'fontsize',fs);
set(h1,'linejoin','round','linestyle','-', ...
    'linewidth',lw,'marker','none','markeredgecolor','auto', ...
    'markerfacecolor','none','markersize',6, ...
    'color',[0 0.447 0.741])
xd1=get(h1,'xdata');
yd2=get(h1,'ydata');
angD=atan2d (yd2, xd1);
%%%%%%%%%%%%%%%
subplot(1,2,2)
h2=rose([2*randn(1e5, 1), pi + 2*randn(1e5, 1)]);
title("rose() angular histogram plot with 8 bins",'fontsize',fs);
set(h2(1),'linejoin','round','linestyle','-', ...
    'linewidth',lw,'marker','none','markeredgecolor','auto', ...
    'markerfacecolor','none','markersize',6, ...
    'color',[0 0.447 0.741])
set(h2(2),'linejoin','round','linestyle','-', ...
    'linewidth',lw,'marker','none','markeredgecolor','auto', ...
    'markerfacecolor','none','markersize',6, ...
    'color',[0.85 0.325 0.098])