%Venn Diagram
close all; clear all; clc;
h=figure('Position',[1 21 1366 670], ...
'Name',strcat('Set Theory',...
 ' - Venn Diagram'));
fs=30; fs2=40;
ha1=annotation ("textbox", [0.1 0 0.85 0.99], "string", ...
             {'Venn Diagram'}, ...
             "fontsize", fs, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);
             
ha2=annotation ("textbox", [0.1 0 0.30 0.50], "string", ...
             {'A'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);

ha3=annotation ("textbox", [0.1 0 1.3 0.50], "string", ...
             {'B'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);


ha4=annotation ("textbox", [0.1 0 0.81 0.50], "string", ...
             {'A \cap B'}, ...
             "fontsize", fs2, 'fontweight','bold',"edgecolor", [1 1 1], ...
             "fitboxtotext", "off", "verticalalignment", "top", ...
             "horizontalalignment", "center",'linestyle','none','linewidth',0.1);             
t = linspace(0,2*pi,1000);
x = [0 cos(t) 0];
y = [0 sin(t) 0];
hp1=patch( x, y,'b');
set(hp1,'edgealpha',0,'edgecolor',[0 0 0], ...
        'facealpha',1,'facecolor',[1 0 0], ...
        'linestyle','-','linewidth',0.5)
        
x = [0 cos(t)-0.75 0];
y = [0 sin(t) 0];
hp2=patch( x, y,'r');
set(hp2,'edgealpha',0,'edgecolor',[0 0 0], ...
        'facealpha',1,'facecolor',[0 0 1], ...
        'linestyle','-','linewidth',0.5)

t = linspace((pi/180)*(180-67.9757),(pi/180)*(180+67.9757),1000);        
x = [0 cos(t) 0];
y = [0 sin(t) 0];
hp3=patch( x, y,'m');
set(hp3,'edgealpha',0,'edgecolor',[0 0 0], ...
        'facealpha',1,'facecolor',[0 1 0], ...
        'linestyle','-','linewidth',0.5)
        
t = linspace((pi/180)*(360-67.9757),(pi/180)*(360+67.9757),1000);        
x = [0 cos(t)-0.75 0];
y = [0 sin(t) 0];
hp4=patch( x, y,'k');
set(hp4,'edgealpha',0,'edgecolor',[0 0 0], ...
        'facealpha',1,'facecolor',[0 1 0], ...
        'linestyle','-','linewidth',0.5)
        
ha1=get(gca,'position');
set(gca,'position',[ha1(1)-0.075 ha1(2)-0.1 ha1(4) ha1(4)])
axis off;
